export const countries =  [
    {abbreviation : "AD", name: "Andorra"},
    {abbreviation : "AE", name: "Emirados Arabes Unidos"},
    {abbreviation : "AF", name: "Afeganistao"},
    {abbreviation : "AG", name: "Antigua e Barbuda"},
    {abbreviation : "AL", name: "Albania"},
    {abbreviation : "AM", name: "Armenia"},
    {abbreviation : "AO", name: "Angola"},
    {abbreviation : "AR", name: "Argentina"},
    {abbreviation : "AT", name: "Austria"},
    {abbreviation : "AU", name: "Australia"},
    {abbreviation : "AZ", name: "Azerbaijao"},
    {abbreviation : "BA", name: "Bosnia e Herzegovina"},
    {abbreviation : "BB", name: "Barbados"},
    {abbreviation : "BD", name: "Bangladesh"},
    {abbreviation : "BE", name: "Belgica"},
    {abbreviation : "BF", name: "Burkina Faso"},
    {abbreviation : "BG", name: "Bulgaria"},
    {abbreviation : "BH", name: "Bahrein"},
    {abbreviation : "BI", name: "Burundi"},
    {abbreviation : "BJ", name: "Benin"},
    {abbreviation : "BN", name: "Brunei"},
    {abbreviation : "BO", name: "Bolivia"},
    {abbreviation : "BR", name: "Brasil"},
    {abbreviation : "BS", name: "Bahamas"},
    {abbreviation : "BT", name: "Butao"},
    {abbreviation : "BW", name: "Botsuana"},
    {abbreviation : "BY", name: "Bielorrussia"},
    {abbreviation : "BZ", name: "Belize"},
    {abbreviation : "CA", name: "Canada"},
    {abbreviation : "CD", name: "Republica Democratica do Congo"},//
    {abbreviation : "CF", name: "Republica Centro Africana"},
    {abbreviation : "CG", name: "Republica do Congo"},//republica do congo
    {abbreviation : "CH", name: "Suiça"},
    {abbreviation : "CI", name: "Costa do Marfim"},
    {abbreviation : "CL", name: "Chile"},
    {abbreviation : "CM", name: "Camaroes"},
    {abbreviation : "CN", name: "China"},
    {abbreviation : "CO", name: "Colombia"},
    {abbreviation : "CR", name: "Costa Rica"},
    {abbreviation : "CU", name: "Cuba"},
    {abbreviation : "CV", name: "Cabo Verde"},
    //{abbreviation : "CW", name: "Curaçau"},
    {abbreviation : "CY", name: "Chipre"},
    {abbreviation : "CZ", name: "Tcheca"},// republica tcheca , checa
    {abbreviation : "DE", name: "Alemanha"},
    {abbreviation: "DJ", name: "Djibouti"},
    {abbreviation : "DK", name: "Dinamarca"},
    {abbreviation : "DM", name: "Dominica"},
    {abbreviation : "DO", name: "Republica Dominicana"},
    {abbreviation : "DZ", name: "Argelia"},
    {abbreviation : "EC", name: "Equador"},
    {abbreviation : "EE", name: "Estonia"},
    {abbreviation : "EG", name: "Egito"},
    //{abbreviation : "EH", name: "Saara Ocidental"},
    {abbreviation : "ER", name: "Eritreia"},
    {abbreviation : "ES", name: "Espanha"},
    {abbreviation : "ET", name: "Etiopia"},
    {abbreviation : "EU", name: "Europa"},
    {abbreviation : "FI", name: "Finlandia"},
    {abbreviation : "FJ", name: "Fiji"},
    {abbreviation : "FM", name: "Micronesia"},
    {abbreviation : "FR", name: "França"},
    {abbreviation : "GA", name: "Gabao"},
    {abbreviation : "GB-ENG", name: "Inglaterra"},
    {abbreviation : "GB-SCT", name: "Escocia"},
    {abbreviation : "GB-WLS", name: "Pais de Gales"},
    {abbreviation : "GB", name: "Reino Unido"},
    {abbreviation : "GD", name: "Granada"},
    {abbreviation : "GE", name: "Georgia"},
    {abbreviation : "GH", name: "Gana"},
    {abbreviation : "GL", name: "Groenlandia"},
    {abbreviation : "GM", name: "Gambia"},
    {abbreviation : "GN", name: "Guine"},
    {abbreviation : "GQ", name: "Guine Equatorial"},
    {abbreviation : "GR", name: "Grecia"},
    {abbreviation : "GT", name: "Guatemala"},
    {abbreviation : "GW", name: "Guine Bissau"},
    {abbreviation : "GY", name: "Guiana"},
    {abbreviation : "HN", name: "Honduras"},
    {abbreviation : "HR", name: "Croacia"},
    {abbreviation : "HT", name: "Haiti"},
    {abbreviation : "HU", name: "Hungria"},
    {abbreviation : "ID", name: "Indonesia"},
    {abbreviation : "IE", name: "Irlanda"},
    {abbreviation : "IL", name: "Israel"},
    {abbreviation : "IN", name: "India"},
    {abbreviation : "IQ", name: "Iraque"},
    {abbreviation : "IR", name: "Ira"},
    {abbreviation : "IS", name: "Islandia"},
    {abbreviation : "IT", name: "Italia"},
    {abbreviation : "JM", name: "Jamaica"},
    {abbreviation : "JO", name: "Jordania"},
    {abbreviation : "JP", name: "Japao"},
    {abbreviation : "KE", name: "Quenia"},
    {abbreviation : "KG", name: "Quirguistao"},
    {abbreviation : "KH", name: "Cambodia"},
    {abbreviation : "KI", name: "Kiribati"},
    {abbreviation : "KM", name: "Comores"},
    {abbreviation : "KN", name: "Sao Cristovao e Nevis"},
    {abbreviation : "KP", name: "Coreia do Norte"},
    {abbreviation : "KR", name: "Coreia do Sul"},
    {abbreviation : "KW", name: "Kuwait"},
    {abbreviation : "KZ", name: "Cazaquistao"},
    {abbreviation : "LB", name: "Libano"},
    {abbreviation : "LC", name: "Santa Lucia"},
    {abbreviation : "LI", name: "Liechtenstein"},
    {abbreviation : "LK", name: "Sri Lanka"},
    {abbreviation : "LR", name: "Liberia"},
    {abbreviation : "LS", name: "Lesoto"},
    {abbreviation : "LT", name: "Lituania"},
    {abbreviation : "LU", name: "Luxemburgo"},
    {abbreviation : "LV", name: "Latonia"},
    {abbreviation : "LY", name: "Libia"},
    {abbreviation : "MA", name: "Morrocos"},
    {abbreviation : "MC", name: "Monaco"},
    {abbreviation : "MD", name: "Moldavia"},
    {abbreviation : "ME", name: "Montenegro"},
    {abbreviation : "MG", name: "Madagascar"},
    {abbreviation : "MH", name: "Ilhas Marshall"},
    {abbreviation : "MK", name: "Macedonia do Norte"},
    {abbreviation : "ML", name: "Mali"},
    {abbreviation : "MM", name: "Myanmar"},
    {abbreviation : "MN", name: "Mongolia"},///////////////////////////////////////
    {abbreviation : "MR", name: "Mauritania"},
    {abbreviation : "MT", name: "Malta"},
    {abbreviation : "MU", name: "Ilhas Mauricio"},
    {abbreviation : "MV", name: "Maldivas"},
    {abbreviation : "MW", name: "Malawi"},
    {abbreviation : "MX", name: "Mexico"},
    {abbreviation : "MY", name: "Malasia"},
    {abbreviation : "MZ", name: "Moçambique"},
    {abbreviation : "NA", name: "Namibia"},
    {abbreviation : "NE", name: "Niger"},
    {abbreviation : "NG", name: "Nigeria"},
    {abbreviation : "NI", name: "Nicaragua"},
    {abbreviation : "NL", name: "Paises Baixos"},
    {abbreviation : "NO", name: "Noruega"},
    {abbreviation : "NP", name: "Nepal"},
    {abbreviation : "NR", name: "Nauru"},
    {abbreviation : "NU", name: "Niue"},
    {abbreviation : "NZ", name: "Nova Zelandia"},
    {abbreviation : "OM", name: "Oma"},
    {abbreviation : "PA", name: "Panama"},
    {abbreviation : "PE", name: "Peru"},
    {abbreviation : "PG", name: "Papua Nova Guine"},
    {abbreviation : "PH", name: "Filipinas"},
    {abbreviation : "PK", name: "Paquistao"},
    {abbreviation : "PL", name: "Polonia"},
    {abbreviation : "PR", name: "Porto Rico"},
    {abbreviation : "PT", name: "Portugal"},
    {abbreviation : "PW", name: "Palau"},
    {abbreviation : "PY", name: "Paraguai"},
    {abbreviation : "QA", name: "Catar"},
    {abbreviation : "RO", name: "Romenia"},
    {abbreviation : "RS", name: "Servia"},
    {abbreviation : "RU", name: "Russia"},
    {abbreviation : "RW", name: "Ruanda"},
    {abbreviation : "SA", name: "Arabia Saudita"},
    {abbreviation : "SB", name: "Ilhas Salomao"},
    {abbreviation : "SC", name: "Seychelles"},
    {abbreviation : "SD", name: "Sudao"},
    {abbreviation : "SE", name: "Suecia"},
    {abbreviation : "SG", name: "Singapura"},
    {abbreviation : "SI", name: "Eslovenia"},
    {abbreviation : "SK", name: "Eslovaquia"},
    {abbreviation : "SL", name: "Serra Leoa"},
    {abbreviation : "SM", name: "San Marino"},
    {abbreviation : "SN", name: "Senegal"},
    {abbreviation : "SO", name: "Somalia"},
    {abbreviation : "SR", name: "Suriname"},
    {abbreviation : "SS", name: "Sudao do Sul"},
    {abbreviation : "ST", name: "Sao Tome e Principe"},
    {abbreviation : "SV", name: "El Salvador"},
    {abbreviation : "SX", name: "Sao Martinho"},
    {abbreviation : "SY", name: "Siria"},
    {abbreviation : "SZ", name: "Suazilandia"},
    {abbreviation : "TD", name: "Chade"},
    {abbreviation : "TG", name: "Togo"},
    {abbreviation : "TH", name: "Tailandia"},
    {abbreviation : "TJ", name: "Tajiquistao"},
    {abbreviation : "TL", name: "Timor-Leste"},
    {abbreviation : "TM", name: "Turcomenistao"},
    {abbreviation : "TN", name: "Tunisia"},
    {abbreviation : "TO", name: "Tonga"},
    {abbreviation : "TR", name: "Turquia"},
    {abbreviation : "TT", name: "Trinidad e Tobago"},
    {abbreviation : "TV", name: "Tuvalu"},
    //{abbreviation : "TW", name: "Taiwan"},
    {abbreviation : "TZ", name: "Tanzania"},
    {abbreviation : "UA", name: "Ucrania"},
    {abbreviation : "UG", name: "Uganda"},
    {abbreviation : "US", name: "Estados Unidos"},
    {abbreviation : "UY", name: "Uruguai"},
    {abbreviation : "UZ", name: "Uzbequistao"},
    {abbreviation : "VA", name: "Vaticano"},
    {abbreviation : "VC", name: "Sao Vicente e Granadinas"},
    {abbreviation : "VE", name: "Venezuela"},
    {abbreviation : "VN", name: "Vietna"},
    {abbreviation : "VU", name: "Vanuatu"},
    {abbreviation : "WS", name: "Samoa"},
    {abbreviation : "XK", name: "Kosovo"},
    {abbreviation : "YE", name: "Iemen"},
    {abbreviation : "ZA", name: "Africa do Sul"},
    {abbreviation : "ZM", name: "Zambia"},
    {abbreviation : "ZW", name: "Zimbabue"}
]